services:
  starbound-server:
    image: docker.io/novac/starbound-docker-steam:latest
    container_name: starbound-server
    stdin_open: true
    tty: true
    environment:
      - STEAM_USER=YOUR_USERNAME
      - WORKSHOP_COLLECTION_IDS=SPACE_SEPARATED_COLLECTION_IDS
      - WORKSHOP_ITEM_IDS=SPACE_SEPARATED_ITEM_IDS
      - USE_OPEN_STARBOUND=false
      - CLEANUP_ORPHANS=true
    ports:
      - "21025:21025"
      - "21025:21025/udp"
      # optional (rcon)
      # - "21026:21026"
    volumes:
      # The game data
      - ./starbound:/home/starbound/starbound
      # The steam data (including cached login credentials and workshop items)
      - ./steam:/home/starbound/Steam
    restart: unless-stopped
